# -*- coding: utf-8 -*-
"""
Created on Wed Aug 15 12:56:54 2018

Problem 2: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

@author: tlane
"""

#Form the Finonacci sequence
fib = [1,2,3]
n = fib[len(fib)-1]

while n:
    n = fib[len(fib)-1] + fib[len(fib)-2]
    if n > 4000000: break
    fib.append(n)

#Sum the even valued terms
evenFib = list()
for n in fib:
    if n % 2 == 0:
        evenFib.append(n)

sumEvenFib = sum(evenFib)        

print(sumEvenFib)